/* 手帐日程流水线：月规划 → 周规划 → 日程 → 本地手帐渲染。 */
const $ = (selector) => document.querySelector(selector);
const DAY_KEYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
const DAY_NAMES = {Mon:"周一", Tue:"周二", Wed:"周三", Thu:"周四", Fri:"周五", Sat:"周六", Sun:"周日"};
let CHARACTERS = [], ACTIVE_CHAR = null, WORKSPACE = null, ACTIVE_DAY = null, ACTIVE_JOURNAL = null;

function esc(value) { return String(value ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]); }
function text(value) { if (value == null) return ""; if (typeof value === "object") return value.zh || value.ko || Object.values(value)[0] || ""; return String(value); }
function toast(message, kind = "") { const el = $("#toast"); el.textContent = message; el.className = `toast show ${kind}`; clearTimeout(toast.timer); toast.timer = setTimeout(() => el.className = "toast", 2600); }
async function api(url, options = {}) { const res = await fetch(url, {headers:{"Content-Type":"application/json"}, ...options}); const data = await res.json().catch(() => ({})); if (!res.ok) throw new Error(data.detail || res.statusText); return data; }
function mondayISO() { const date = new Date(); const day = date.getDay() || 7; date.setDate(date.getDate() - day + 1); return date.toISOString().slice(0, 10); }
function workspaceWeek() { return WORKSPACE?.weeks?.[String(WORKSPACE.current_week_no || 1)] || {}; }
function updateEnvInputs() { const env = WORKSPACE?.env || {}; $("#season").value = env.season || ""; $("#city").value = env.city || ""; $("#monthStart").value = env.month_start_date || mondayISO(); $("#weather").value = env.weather || ""; $("#dialogue").value = env.dialogue || ""; }
function readEnv() { return {season:$("#season").value.trim(), city:$("#city").value.trim(), month_start_date:$("#monthStart").value, weather:$("#weather").value.trim(), dialogue:$("#dialogue").value.trim()}; }

async function init() { try { CHARACTERS = await api("/api/characters"); renderCharacters(); const id = new URLSearchParams(location.search).get("char"); if (id) selectCharacter(id); else if (CHARACTERS.length) selectCharacter(CHARACTERS[0].char_id); } catch (err) { toast("角色列表加载失败：" + err.message, "err"); } }
function filteredCharacters() { const q = $("#search").value.trim().toLowerCase(); return CHARACTERS.filter(c => !q || `${c.name || ""} ${c.char_id || ""}`.toLowerCase().includes(q)); }
function renderCharacters() { const box = $("#chars"); box.innerHTML = filteredCharacters().map(c => { const cover = c.cover_url ? `<img src="${esc(c.cover_url)}" loading="lazy">` : esc((c.name || "?").slice(0, 1)); return `<div class="char ${c.char_id === ACTIVE_CHAR ? "on" : ""}" data-id="${esc(c.char_id)}"><div class="avatar">${cover}</div><div style="min-width:0"><div class="char-name">${esc(c.name || "未命名角色")}</div><div class="char-meta">${esc(c.char_id)}${c.lang_name ? " · " + esc(c.lang_name) : ""}</div></div></div>`; }).join("") || '<div class="journal-empty">没有匹配角色</div>'; box.querySelectorAll(".char").forEach(el => el.onclick = () => selectCharacter(el.dataset.id)); }
async function selectCharacter(charId) { ACTIVE_CHAR = charId; renderCharacters(); const meta = CHARACTERS.find(c => c.char_id === charId) || {}; $("#empty").hidden = true; $("#workbench").hidden = false; $("#charTitle").textContent = meta.name || charId; $("#charSub").textContent = `${charId}${meta.lang_name ? " · " + meta.lang_name : ""}`; try { WORKSPACE = await api(`/api/schedule_pipeline/${encodeURIComponent(charId)}`); } catch (err) { toast("日程档案加载失败：" + err.message, "err"); return; } ACTIVE_DAY = null; ACTIVE_JOURNAL = null; updateEnvInputs(); render(); }

async function pollTask(taskId) { for (;;) { await new Promise(resolve => setTimeout(resolve, 1800)); const task = await api(`/api/tasks/${taskId}`); if (task.status === "done") return task.result; if (task.status === "error") throw new Error(task.error || "生成失败"); } }
async function runTask(url, body, button, label) { const original = button.textContent; button.disabled = true; button.innerHTML = `<span class="spin"></span> ${label}`; try { const {task_id} = await api(url, {method:"POST", body:JSON.stringify(body)}); WORKSPACE = await pollTask(task_id); render(); toast("生成完成", "ok"); return true; } catch (err) { toast("生成失败：" + err.message, "err"); return false; } finally { button.disabled = false; button.textContent = original; } }
async function persistWorkspace() { if (!WORKSPACE || !ACTIVE_CHAR) return; try { WORKSPACE = await api(`/api/schedule_pipeline/${encodeURIComponent(ACTIVE_CHAR)}`, {method:"PUT", body:JSON.stringify({workspace:WORKSPACE})}); } catch (err) { toast("保存失败：" + err.message, "err"); } }

function archiveCurrent() { if (!WORKSPACE?.monthly_plan) return; const records = JSON.parse(localStorage.getItem("popop-schedule-history-v1") || "[]"); records.unshift({id:Date.now().toString(36), at:Date.now(), char_id:ACTIVE_CHAR, char_name:$("#charTitle").textContent, workspace:WORKSPACE}); localStorage.setItem("popop-schedule-history-v1", JSON.stringify(records.slice(0, 20))); }
async function generateMonth(continueMonth) { if (continueMonth && WORKSPACE?.monthly_plan) archiveCurrent(); const env = readEnv(); await runTask("/api/schedule_pipeline/month", {...env, char_id:ACTIVE_CHAR, continue_month:continueMonth}, continueMonth ? $("#nextMonth") : $("#genMonth"), continueMonth ? "承接中" : "规划中"); }
function weekNo() { return Number(WORKSPACE?.current_week_no || 1); }
async function generateWeek() { await runTask("/api/schedule_pipeline/week", {char_id:ACTIVE_CHAR, week_no:weekNo()}, $("#genWeek"), "生成中"); }
async function generateDays() { const days = [...document.querySelectorAll(".day-check:checked")].map(el => el.value); if (!days.length) return toast("请至少选择一天", "err"); await runTask("/api/schedule_pipeline/days", {char_id:ACTIVE_CHAR, week_no:weekNo(), days}, $("#genDays"), "串行生成中"); }

function renderMonth() { const out = $("#monthOut"), plan = WORKSPACE?.monthly_plan; if (!plan) { out.className = "journal-empty"; out.textContent = "先选定环境，再生成这个月的生活骨架。"; return; } const threads = (plan.goal_threads || []).slice(0, 6).map(t => `<div class="thread"><div class="thread-top"><span class="tag ${esc(t.type || "")}">${esc(t.type || "目标")}</span><span class="thread-name">${esc(text(t.name))}</span></div><div class="thread-note">${esc(text(t.progress_pct))}${t.note ? " · " + esc(text(t.note)) : ""}</div></div>`).join(""); const weeks = (plan.weeks || []).map(w => `<div class="week-card ${Number(w.week_no) === weekNo() ? "on" : ""}"><b>第 ${esc(w.week_no)} 周 · ${esc(w.pace || "")}</b><span>${esc((w.focus_thread || []).join(" / ") || w.week_brief || "待展开")}</span></div>`).join(""); out.className = ""; out.innerHTML = `<div class="month-label">${esc(plan.month_label || "本月规划")}</div><div class="month-theme">${esc(plan.month_theme || "")}</div>${threads}<div class="week-cards">${weeks}</div>`; }
function renderWeek() { const plan = WORKSPACE?.monthly_plan, picker = $("#weekPick"), out = $("#weekOut"), btn = $("#genWeek"); if (!plan) { picker.innerHTML = '<span class="journal-empty">先生成月规划</span>'; btn.disabled = true; out.className = "journal-empty"; out.textContent = "第 1 周会随月规划一并生成。"; return; } picker.innerHTML = [1,2,3,4].map(n => `<button class="pick ${n === weekNo() ? "on" : ""}" data-week="${n}">第 ${n} 周</button>`).join(""); picker.querySelectorAll(".pick").forEach(b => b.onclick = () => { WORKSPACE.current_week_no = Number(b.dataset.week); ACTIVE_DAY = null; ACTIVE_JOURNAL = null; render(); persistWorkspace(); }); const week = workspaceWeek(), weekly = week.weekly_plan; btn.disabled = false; if (!weekly || !Object.keys(weekly).length) { out.className = "journal-empty"; out.textContent = "生成选中周的具体安排。"; return; } const themes = DAY_KEYS.map(key => { const t = weekly.daily_themes?.[key] || {}; return `<div class="theme-row"><b>${DAY_NAMES[key]}</b><div>${esc(t.theme || "—")}<span>${esc(t.focus || "")}</span></div></div>`; }).join(""); out.className = ""; out.innerHTML = `<div class="plan-goal">${esc(weekly.weekly_goal || "本周目标")}</div>${weekly.milestone ? `<div class="action-note">★ ${esc(weekly.milestone)}</div>` : ""}<ul class="list">${(weekly.sub_goals || []).map(x => `<li>${esc(text(x))}</li>`).join("")}</ul><div class="daily-themes">${themes}</div>`; }
function checks(days, className, done) { return DAY_KEYS.map(k => `<label class="check"><input class="${className}" type="checkbox" value="${k}" ${days.includes(k) ? "checked" : ""}>${DAY_NAMES[k]}${done?.includes(k) ? " ✓" : ""}</label>`).join(""); }
function renderDays() { const pick = $("#dayPick"), btn = $("#genDays"), tabs = $("#dayTabs"), out = $("#dayOut"), week = workspaceWeek(), weekly = week.weekly_plan, days = week.day_plans || {}; if (!weekly || !Object.keys(weekly).length) { pick.innerHTML = '<span class="journal-empty">先生成周规划</span>'; btn.disabled = true; tabs.innerHTML = ""; out.className = "journal-empty"; out.textContent = "日程会承接前一天的真实结果。"; return; } pick.innerHTML = checks(DAY_KEYS, "day-check", Object.keys(days)); btn.disabled = false; const keys = DAY_KEYS.filter(k => days[k]); if (!ACTIVE_DAY || !days[ACTIVE_DAY]) ACTIVE_DAY = keys[0] || null; tabs.innerHTML = keys.map(k => `<button class="tab ${k === ACTIVE_DAY ? "on" : ""}" data-day="${k}">${DAY_NAMES[k]}</button>`).join(""); tabs.querySelectorAll(".tab").forEach(b => b.onclick = () => { ACTIVE_DAY = b.dataset.day; renderDays(); }); const day = days[ACTIVE_DAY]; if (!day) { out.className = "journal-empty"; out.textContent = "选择日期后按顺序串行生成；最后一天会结算本周。"; return; } const opening = day.opening_state || {}; const slots = (day.daily_schedule || []).map(s => `<div class="slot"><time>${esc(s.start_time || "")}<br>${esc(s.end_time || "")}</time><b>${esc(text(s.activity_name))}</b><span class="loc">@${esc(text(s.location))}</span><div class="detail">${esc(text(s.detail))}</div>${s.echo ? `<div class="echo">↳ 与用户的回声：${esc(text(s.echo))}</div>` : ""}</div>`).join(""); out.className = ""; out.innerHTML = `<div class="day-state">${esc([opening.wake_time && "起床 " + opening.wake_time, text(opening.sleep), text(opening.body), text(opening.mood_carryover)].filter(Boolean).join(" · "))}</div>${slots}<div class="action-note">📝 ${esc(text(day.day_summary))}</div>`; }
function dateFor(day) { const iso = WORKSPACE?.env?.month_start_date || mondayISO(); const base = new Date(`${iso}T12:00:00`); base.setDate(base.getDate() + (weekNo() - 1) * 7 + DAY_KEYS.indexOf(day)); return base; }
function journalHtml(day, plan) { const date = dateFor(day), stamp = `${date.getMonth()+1}.${date.getDate()}`; const slots = (plan.daily_schedule || []).map(s => `<article><time>${esc(s.start_time || "")}</time><div><b>${esc(text(s.activity_name))}</b><small> ${esc(text(s.location))}</small><p>${esc(text(s.detail))}</p></div></article>`).join(""); const todos = [...(plan.todo_tracking?.completed_todo || []).map(x => `☑ ${esc(text(x))}`), ...(plan.todo_tracking?.todo || []).map(x => `☐ ${esc(text(x))}`)].slice(0, 5).map(x => `<li>${x}</li>`).join(""); return `<!doctype html><html><head><meta charset="utf-8"><style>*{box-sizing:border-box}body{margin:0;background:#ded7cb;color:#302d29;font-family:-apple-system,"PingFang SC",sans-serif;padding:18px}.page{max-width:520px;min-height:690px;margin:auto;position:relative;overflow:hidden;padding:34px 36px;background:#fffaf0;box-shadow:0 10px 25px #91877966}.page:before{content:"";position:absolute;inset:0;opacity:.24;background-image:radial-gradient(#bcaa9244 .7px,transparent .8px);background-size:7px 7px;pointer-events:none}.top,.content{position:relative}.top{display:flex;align-items:flex-end;gap:12px;border-bottom:2px solid #c96442;padding-bottom:16px}.day{font:italic 76px/0.8 Georgia,serif;color:#c96442;letter-spacing:-3px}.meta{font-size:11px;line-height:1.7;color:#756e64}.mood{margin:20px 0;padding:10px 12px;background:#f4eadf;border-radius:10px;font-size:12px;line-height:1.6}.content article{display:grid;grid-template-columns:57px 1fr;gap:11px;padding:11px 0;border-bottom:1px dashed #dccfbf}.content time{font:700 11px Georgia,serif;color:#b35a3d}.content b{font-size:13px}.content small{font-size:10px;color:#887f74}.content p{font-size:11.5px;line-height:1.55;margin:4px 0 0}.todos{margin-top:22px;border:1px solid #e4d7c9;border-radius:10px;padding:10px 13px}.todos b{font-size:11px;color:#b35a3d}.todos ul{padding:0;margin:6px 0 0;list-style:none;font-size:11px;line-height:1.8}.sticker{position:absolute;right:-10px;bottom:34px;width:93px;height:93px;border-radius:50% 46% 52% 44%;background:#dce8d4;border:4px solid #fffaf0;transform:rotate(-12deg);display:grid;place-items:center;font-size:34px;box-shadow:0 4px 8px #92795b33}.quote{margin-top:17px;font:italic 14px/1.6 Georgia,serif;color:#655b51}</style></head><body><main class="page"><div class="top"><div class="day">${stamp}</div><div class="meta">${DAY_NAMES[day]}<br>${esc(WORKSPACE?.env?.weather || "ordinary day")}</div></div><div class="mood">${esc(text(plan.state_update?.daily_theme) || text(plan.opening_state?.mood_carryover) || "慢慢把今天过完。")}</div><div class="content">${slots}</div>${todos ? `<div class="todos"><b>TO DO / DONE</b><ul>${todos}</ul></div>` : ""}<div class="quote">${esc(text(plan.day_summary || ""))}</div><div class="sticker">${plan.moments?.length ? "✦" : "☕"}</div></main></body></html>`; }
async function generateJournals() { const selected = [...document.querySelectorAll(".journal-check:checked")].map(el => el.value); if (!selected.length) return toast("请至少选择一天", "err"); const week = workspaceWeek(), journals = week.journals || (week.journals = {}), days = week.day_plans || {}; selected.forEach(day => { if (days[day]) journals[day] = {html:journalHtml(day, days[day]), rendered_at:Date.now()}; }); ACTIVE_JOURNAL = selected.find(d => journals[d]) || ACTIVE_JOURNAL; await persistWorkspace(); renderJournals(); toast("手帐已渲染", "ok"); }
function renderJournals() { const pick = $("#journalPick"), btn = $("#genJournals"), tabs = $("#journalTabs"), out = $("#journalOut"), week = workspaceWeek(), days = week.day_plans || {}, journals = week.journals || {}, generated = DAY_KEYS.filter(k => days[k]); if (!generated.length) { pick.innerHTML = '<span class="journal-empty">先生成日程</span>'; btn.disabled = true; tabs.innerHTML = ""; out.className = "journal-empty"; out.textContent = "手帐会由已生成的日程直接渲染，不会再改写事件。"; return; } pick.innerHTML = checks(generated, "journal-check", Object.keys(journals)); btn.disabled = false; const rendered = generated.filter(k => journals[k]?.html); if (!ACTIVE_JOURNAL || !journals[ACTIVE_JOURNAL]) ACTIVE_JOURNAL = rendered[0] || null; tabs.innerHTML = rendered.map(k => `<button class="tab ${k === ACTIVE_JOURNAL ? "on" : ""}" data-journal="${k}">${DAY_NAMES[k]}</button>`).join(""); tabs.querySelectorAll(".tab").forEach(b => b.onclick = () => { ACTIVE_JOURNAL = b.dataset.journal; renderJournals(); }); if (!ACTIVE_JOURNAL) { out.className = "journal-empty"; out.textContent = "选定日期后渲染手帐日页。"; return; } out.className = "journal-preview"; out.innerHTML = `<iframe title="${DAY_NAMES[ACTIVE_JOURNAL]}手帐" sandbox="allow-same-origin" srcdoc="${esc(journals[ACTIVE_JOURNAL].html)}"></iframe>`; }
function render() { renderMonth(); renderWeek(); renderDays(); renderJournals(); }

function exportPipeline() { if (!WORKSPACE?.monthly_plan) return toast("没有可导出的日程", "err"); const plan = WORKSPACE.monthly_plan, lines = [`# ${$("#charTitle").textContent} · 角色日程手帐流水线`, "", `> ${Object.entries(WORKSPACE.env || {}).filter(([,v]) => v).map(([k,v]) => `${k}: ${v}`).join(" · ")}`, "", `## 月规划 · ${plan.month_label || ""}`, plan.month_theme || ""]; (plan.goal_threads || []).forEach(t => lines.push(`- [${t.type || ""}] ${text(t.name)} · ${text(t.progress_pct)} · ${text(t.note)}`)); Object.entries(WORKSPACE.weeks || {}).sort(([a],[b]) => Number(a)-Number(b)).forEach(([no, week]) => { const p = week.weekly_plan || {}; lines.push("", `## 第 ${no} 周`, `- 目标：${p.weekly_goal || ""}`, `- 里程碑：${p.milestone || ""}`); Object.entries(week.day_plans || {}).forEach(([key, day]) => { lines.push("", `### ${DAY_NAMES[key]}`, `- ${text(day.day_summary)}`); (day.daily_schedule || []).forEach(s => lines.push(`  - ${s.start_time}-${s.end_time} ${text(s.activity_name)} @${text(s.location)}：${text(s.detail)}`)); }); }); const blob = new Blob([lines.join("\n")], {type:"text/markdown;charset=utf-8"}), link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `${$("#charTitle").textContent}_日程流水线.md`; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 300); }
function renderHistory() { const list = JSON.parse(localStorage.getItem("popop-schedule-history-v1") || "[]"), box = $("#historyList"); box.innerHTML = list.length ? list.map(item => `<div class="history-item"><b>${esc(item.char_name)} · ${esc(item.workspace?.monthly_plan?.month_label || "月规划")}</b><span>${new Date(item.at).toLocaleString()} · 已存 ${Object.keys(item.workspace?.weeks || {}).length} 周</span><button class="mini" data-load="${esc(item.id)}">载入工作区</button><button class="mini" data-export="${esc(item.id)}">导出 JSON</button><button class="mini" data-delete="${esc(item.id)}">删除</button></div>`).join("") : '<div class="journal-empty">还没有历史档案。承接下个月前会自动保存当前月。</div>'; box.querySelectorAll("[data-load]").forEach(b => b.onclick = async () => { const target = list.find(x => x.id === b.dataset.load); if (!target || target.char_id !== ACTIVE_CHAR) return toast("请先在左侧选择对应角色", "err"); WORKSPACE = target.workspace; updateEnvInputs(); await persistWorkspace(); render(); $("#historyModal").classList.remove("show"); }); box.querySelectorAll("[data-delete]").forEach(b => b.onclick = () => { localStorage.setItem("popop-schedule-history-v1", JSON.stringify(list.filter(x => x.id !== b.dataset.delete))); renderHistory(); }); box.querySelectorAll("[data-export]").forEach(b => b.onclick = () => { const target = list.find(x => x.id === b.dataset.export); const blob = new Blob([JSON.stringify(target?.workspace, null, 2)], {type:"application/json"}), link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "日程流水线历史.json"; link.click(); }); }

$("#search").oninput = renderCharacters; $("#genMonth").onclick = () => generateMonth(false); $("#nextMonth").onclick = () => generateMonth(true); $("#genWeek").onclick = generateWeek; $("#genDays").onclick = generateDays; $("#genJournals").onclick = generateJournals; $("#exportBtn").onclick = exportPipeline; $("#historyBtn").onclick = () => {renderHistory(); $("#historyModal").classList.add("show")}; $("#closeHistory").onclick = () => $("#historyModal").classList.remove("show"); $("#clearHistory").onclick = () => {if (confirm("清空本机历史档案？")) {localStorage.removeItem("popop-schedule-history-v1"); renderHistory();}}; $("#historyModal").onclick = e => {if (e.target.id === "historyModal") e.currentTarget.classList.remove("show")}; ["season","city","monthStart","weather","dialogue"].forEach(id => $("#"+id).addEventListener("change", () => { if (WORKSPACE) {WORKSPACE.env = readEnv(); persistWorkspace();} }));
init();
